version: '3.9'

services:
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: nginx
    ports:
      - "80:8080"
    environment:
      ENVSUBST: $\{NGINX_PORT\} $\{FASTAPI_ENDPOINT\} $\{FASTAPI_PORT\} $\{VUE_ENDPOINT\} $\{VUE_PORT\}
    depends_on:
      fastapi:
        condition: service_healthy
      vue:
        condition: service_healthy
  vue:
    container_name: vue
    hostname: vue
    build:
      context: vue
      args:
        DEV_MODE: compose
    healthcheck:
      test: curl --fail http://localhost:$${VUE_PORT} || exit 1
      start_period: 10s
      interval: 1s
      retries: 3
      timeout: 1s
    #ports:
    #   - "8080:8080"
    environment:
      VUE_PORT: 8080
    volumes:
      - ${PWD}/vue/src:/app/src:rw
  fastapi:
    container_name: fastapi
    hostname: fastapi
    build:
      context: fastapi
      args:
        DEV_MODE: compose
    restart: always
    healthcheck:
      test: curl --fail http://localhost:$${UVICORN_PORT}/healthz || exit 1
      start_period: 1s
      interval: 1s
      retries: 2
      timeout: 1s
    #ports:
    #  - "3000:3000"
    environment:
      UVICORN_PORT: 3000
    volumes:
      - ${PWD}/fastapi/src/:/app/src
